### ISSUE TITLE
TRestRun InitFromConfigFile is implementing addProcess

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#266]
I was just wondering if the code inside `if (keydeclare == "addProcess") {` at `TRestRun::InitFromConfigFile` is now obsolete and should be removed? We are now implementing `addProcess` inside `TRestProcessRunner` so, I guess those lines could be removed from `TRestRun`?

Also, how/where the `observable="all"` statement is interpreted? I would like to allow the plural too. `observables="all"` since I am always making the wrong guess there.

**Comment by nkx111** [comment]
> I was just wondering if the code inside if (keydeclare == "addProcess") { at TRestRun::InitFromConfigFile is now obsolete and should be removed? We are now implementing addProcess inside TRestProcessRunner so, I guess those lines could be removed from TRestRun?

Adding process at `<TRestRun` section was made possible, because `external processes` are actually managed by TRestRun to read binary files. Although we usually define them inside `<TRestProcessRunner` section. So removing these lines shall not influence our work. 

> Also, how/where the observable="all" statement is interpreted? I would like to allow the plural too. observables="all" since I am always making the wrong guess there. 

It is implemented [here](https://github.com/rest-for-physics/framework/blob/f6874dfb3705449f77098f83c2f353cb56f45d75/source/framework/core/src/TRestEventProcess.cxx#L194)

**Comment by jgalan** [comment]
Ok, I will remove it then
