### ISSUE TITLE
Problem using `units`

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#268]
I am experiencing some issues with units, I thought the following should return the proper unit scaling factor, but seems to be not working.

```
restRoot
root [0] 1.*units("eV")
(double) 1.0000000
```

I would expect that it returns 0.001 since the standard unit is keV.

There is something I am missing?

**Comment by nkx111** [comment]
> I would expect that it returns 0.001 since the standard unit is keV.

Actually it shall return 1000 as supposed. This logic confused us many times but it was as it since very early time. `*` units means to convert the value from standard unit from custom unit. So 1(keV) converted into eV unit would be 1000.

I cannot reproduce this problem. Which REST version are you using?

**Comment by jgalan** [comment]
Ok, now the problem is solved in my current branch.

It is probably due to the fact that I reverted the following commit that was causing the pipeline to fail.


93e7923
