### ISSUE TITLE
pull-submodules is not pulling the requested branch?

### ISSUE THREAD

**Issue by jgalan** [rest-for-physics/framework#470]
It seems that the pull-submodules.py script is not pulling the corresponding branch for jovoy-mirror_fix, which exists inside https://github.com/rest-for-physics/axionlib/tree/jvonoy-mirror_fix

Instead it seems to be pulling the last commit from the axionlib master branch.

https://github.com/rest-for-physics/framework/actions/runs/6001773909/job/16276684495?pr=469

The pipeline is trying to run the following:

<img width="579" alt="Screenshot 2023-08-28 at 18 16 06" src="https://github.com/rest-for-physics/framework/assets/12447509/d5fda019-7440-4425-b8eb-4e731b590346">

But the commit hash corresponds to axionlib:master

![Screenshot 2023-08-28 at 17 38 05](https://github.com/rest-for-physics/framework/assets/12447509/4809981a-acb7-44b1-a950-4482cd17165b)

**Comment by juanangp** [comment]
I think that this issue is not related with `pull-submodules.py` unless you can reproduce the issue locally.

I think that the references to the branches are somehow not properly updated in the validation pipeline, so the `jvonoy-mirror-fix` branch is not found or outdated.

A work around is to do a push to the `jvonoy-mirror-fix` branch in `axionlib`.

There is not an easy fix for this issue, although I think that can be addressed with this PR https://github.com/rest-for-physics/framework/pull/405

**Comment by juanangp** [comment]
I found the issue, branch names doesn't match, in `axionlib` is written as `jvonoy-mirror_fix` while in framework is `jovoy-mirror_fix`.

**Comment by jgalan** [comment]
Ouch! Thats a good reason!

I will warn @jovoy
